config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions', confirmations: 'confirmations' }
  root to: "application#index"
  resources :requests, only: [:show, :index, :new, :create] do
    collection do
      get :search
    end
  end
  
  resources :users, only: [:show]
  resources :reviews, only: [:create]
  resources :profiles, only: [:edit, :show, :update]
  resources :messages, only: [:new, :create, :index]
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_many :requests
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: "User", foreign_key: :sender_id
  belongs_to :receiver, class_name: "User", foreign_key: :receiver_id
  
  def history
    message_history = []
    message = self
    message_history << message
    
    loop do
      break if message.replied_to_id.nil?
      message = Message.find(message.replied_to_id)
      message_history << message
    end
    
    message_history
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_many :requests
  belongs_to :user
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :profile
  belongs_to :activity
  
  geocoded_by :geocoder_input
  after_validation :geocode
  
  def geocoder_input
    "#{self.town_city}, #{self.country}"
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :reviewer, class_name: "User"
  belongs_to :reviewed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
  has_one :profile
  
  has_many :reviews, foreign_key: "reviewed_id"
  has_many :reviewed, class_name: "Review", foreign_key: "reviewer_id"
  
  has_many :received_messages, class_name: "Message", foreign_key: :receiver_id
  has_many :sent_messages, class_name: "Message", foreign_key: :sender_id
  
  after_create do
    profile = Profile.create(user_id: self.id)
    self.update(profile_id: profile.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def index
    @activities = Activity.all.map{ |activity| [activity.name.downcase, activity.id] }
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = current_user.received_messages.order(created_at: :desc)
    @threads = get_unique_senders(@messages)

    params[:sender_id] = @threads.first.sender_id unless params[:sender_id]
    
    @message = Message.new
    
    @thread_messages = Message.where("(receiver_id = ? OR sender_id = ?) AND (receiver_id = ? OR sender_id = ?)", params[:sender_id], params[:sender_id], current_user.id, current_user.id)

    respond_to do |format|
      format.json { render json: @thread_messages }
      format.html
    end
  end
  
  def new
    @message = Message.new
    @receiver = User.find(params[:receiver_id])
  end
  
  def create
    @message = Message.create!(message_params)
    
    respond_to do |format|
      format.html { redirect_to profile_path(params[:message][:receiver_id], sent: "true") }
      format.js
    end
  end
  
  private
  
  def message_params
    params.require(:message).permit(:receiver_id, :sender_id, :body)
  end
  
  def get_unique_senders(messages)
    uniques = []
    sender_ids = []
    
    messages.each do |message|
      unless sender_ids.include? message.sender_id
        uniques << message
      end
      
      sender_ids << message.sender_id
    end
    
    uniques
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def edit
    @profile = Profile.find(params[:id])
  end
  
  def update
    Profile.find(params[:id]).update(profile_params)
    redirect_to profile_path(params[:id])
  end

  def show
    @profile = Profile.find(params[:id])
    @requests = @profile.requests
    @review = Review.new
    @rating_options = [["0 Stars",0],["1 Star",1],["2 Stars",2],["3 Stars",3],["4 Stars",4],["5 Stars",5]].reverse
    @reviews = @profile.user.reviews if @profile.user
    @sent = true if params[:sent] == "true"
  end
  
  private
  
  def profile_params
    params.require(:profile).permit(:username, :town_city, :country, :image_url, :cover_image_url, :user_id, :biography)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController 
  def new
    @background_image = "background-registration"  
    super
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def search
    if params[:search][:town_city]
      @requests = Request.search(conditions: {activity_id: params[:search][:activity_id], town_country: params[:search][:town_country], country: params[:search][:country]})
      
      @activity = Activity.find(params[:search][:activity_id]).name.downcase
      @activity_id = params[:search][:activity_id]
      @town_city = params[:search][:town_city]
      @country = params[:search][:country]
      @map_lat_lng = Geocoder.coordinates("#{@town_city}, #{@country}")
      @map_lat = @map_lat_lng[0]
      @map_lng = @map_lat_lng[1]
    else
      ne_lat = params[:search][:northEastLat].to_f
      ne_lng = params[:search][:northEastLng].to_f
      map_center_lat = params[:search][:mapCenterLat].to_f
      map_center_lng = params[:search][:mapCenterLng].to_f

      distance = Geocoder::Calculations.distance_between([ne_lat,ne_lng], [map_center_lat,map_center_lng])
      @requests = Request.near([map_center_lat, map_center_lng], distance).where(activity_id: params[:search][:activity_id])
    end
    
    respond_to do |format|
      format.html
      format.json { render json: @requests.to_json(include: :profile) }
    end
  end
  
  def new
    @request = Request.new
    @activities = Activity.all.map{ |activity| [activity.name.downcase, activity.id] }
    @profile = Profile.find(current_user.profile_id)
    @requests = @profile.requests
  end
  
  def create
    @request = Request.create!(request_params)
    
    respond_to do |format|
      format.html { redirect_to new_request_path }
      format.js 
    end
  end
  
  def show
    
  end
  
  private
  
  def request_params
    params.require(:request).permit(:profile_id, :activity_id, :town_city, :country)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.create!(review_params)

    respond_to do |format|
      format.html { redirect_to profile_path @review.reviewed_id }
      format.js
    end
  end
  
  private
  
  def review_params
    params.require(:review).permit(:title, :rating, :body, :reviewed_id, :reviewer_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController 
  def new
    @background_image = "background-log-in"  
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.haml
.content-wrapper.home-wrapper
  .front-content
    %h1 MeetMeet
    .search-box
      = form_tag search_requests_path, method: :get, class: "nl-form", id: "nl-form" do

        I want to
        .nl-field
          %a.field-toggle select activity
          %ul
            %li select activity...
            - @activities.each_with_index do |activity, index|
              %li.select-option(data-id="#{index}")= activity[0]
          = select_tag("search[activity_id]", options_for_select(@activities), class: "inline-select", id: "activities-select")

        in
        .nl-field
          %a.field-toggle#town_city{href: ""} enter town/city
          %ul.text-input
            %li
              = text_field_tag "search[town_city]", nil, placeholder: "enter town/city", class: "inline-text", id: "town-city-input"
              .nl-next >

        ,
        .nl-field
          %a.field-toggle#country{href: ""} enter country
          %ul.text-input
            %li
              = text_field_tag "search[country]", nil, placeholder: "enter country", class: "inline-text", id: "country-input"
              .nl-next >

        .clearfix

        = submit_tag "Find People!", class: "inline-button"

        .nl-overlay

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MeetMeet</title>
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= @background_image %>">
  <div class="container-fluid">
    <div class="topbar row">
      <div class="col-sm-2">
        <%= link_to "MeetMeet", root_path, class: "home-button" %>
      </div>
      
      <div class="col-sm-10 text-right">
        <% if current_user %>
          <%= link_to "My Profile", profile_path(current_user.profile_id) %>
          <%= link_to "Inbox", messages_path %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Register", new_user_registration_path %>
          <%= link_to "Log In", new_user_session_path %>
        <% end %>
      </div>
    </div>
  </div>

  <%= yield %>
  
  <p class="notice center-translucent col-sm-6 col-sm-offset-3 text-center"><%= notice %></p>
  <p class="alert center-translucent col-sm-6 col-sm-offset-3 text-center"><%= alert %></p>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBa1wy21lyE-MoY1Hes4QYQeOrSPpaBhPM&callback=initMap" async defer></script>
</body>
</html>

app/views/messages/_message.html.haml
.message-container{class: "#{"self" if message.sender_id == current_user.id}"}
  .thumbnail-container{style: "background-image: url(#{message.sender.profile.image_url})"}
  .info-container
    %h3= message.sender.profile.username
    %p= message.body

app/views/messages/create.js.erb
$('#message-show').append("<%= escape_javascript(render partial: 'messages/message', locals: { message: @message }) %>");

$('#message_body').val("");

app/views/messages/index.html.haml
.inbox
  .row.h-100
    .col-sm-8.col-sm-offset-2.inbox-container
      .threads.col-sm-4
        - @threads.each do |thread|
          %a{href: "?sender_id=#{thread.sender_id}"}
            .thread-container
              .thumbnail-container{style: "background-image: url(#{thread.sender.profile.image_url})"}
              .info-container
                %span= thread.sender.profile.username
                %br
                %p= thread.body[0,23] + "..."
      #message-show.col-sm-8
        = render @thread_messages
      .reply.col-sm-8
        = form_for @message, url: messages_path, method: :post, remote: true do |f|
          = f.text_area :body, placeholder: "Write reply"
          = f.hidden_field :sender_id, value: current_user.id
          = f.hidden_field :receiver_id, value: params[:sender_id] || @thread_messages.first.sender_id
          .form-options
            = f.submit "Send Reply", class: "pull-right"
            .clearfix

app/views/messages/new.html.haml
.col-sm-8.col-sm-offset-2.pt-30
  %h2= "Send message to #{@receiver.profile.username}"
  = form_for @message, url: messages_path, method: "POST" do |f|
    = hidden_field_tag "message[sender_id]", current_user.id
    = hidden_field_tag "message[receiver_id]", @receiver.id
    = f.text_area :body, placeholder: "Message", class: "form-control"
    = f.submit "Send Message", class: "form-control btn btn-info", id: "send_message"

app/views/profiles/edit.html.haml
.content-wrapper
  .col-sm-6.col-sm-offset-3.edit-profile
    %h2 Edit Profile
    = form_for @profile do |f|
      %fieldset
        %h3 Username
        = f.text_field :username, class: "form-control"
      %fieldset
        %h3 Profile Picture
        = f.text_field :image_url, class: "form-control"
      %fieldset
        %h3 Cover Photo
        = f.text_field :cover_image_url, class: "form-control"
      %fieldset
        %h3 Biography
        = f.text_area :biography, class: "form-control"
      %fieldset
        %h3 Location
        = f.text_field :town_city, class: "form-control"
        = f.text_field :country, class: "form-control"
        = f.submit "Save Changes", class: "btn btn-info form-control"

app/views/profiles/show.html.haml
- if @sent
  .notice Your message has been sent!
  
.content-wrapper
  .col-sm-8.col-sm-offset-2
    .row
      .col-sm-12.cover{style: "background-image: url(#{@profile.cover_image_url})"}
  .col-sm-8.col-sm-offset-2.profile
    .row
      .col-sm-4.profile-sidebar
        = image_tag @profile.image_url || "profile_placeholder"
        %h2= @profile.username
        %p= "Location: #{@profile.town_city}, #{@profile.country}"
        - if current_user && @profile.user_id == current_user.id
          = link_to "Edit Profile", edit_profile_path(@profile.id), class: "btn btn-meet form-control"

        - unless current_user && @profile.user_id == current_user.id
          = button_to "send_message", new_message_path, method: :get, params: { receiver_id: @profile.user.id}, class: "btn btn-default form-control"

      .col-sm-8.pr-0
        .col-sm-12
          .row
            .profile-info-wrapper
              %h3= "About #{@profile.username}"
              %p= @profile.biography.html_safe if @profile.biography

            .profile-requests.profile-info-wrapper
              %h3= "#{@profile.username} wants to:"
              - @requests.each do |request|
                %p.form-control= "#{request.activity.name} in #{request.town_city}, #{request.country}"
              
              - if current_user && @profile.user_id == current_user.id
                = button_to "Add new request", new_request_path, method: :get, class: "btn btn-meet form-control message-button"
              - else
                = button_to "Send a message and MeetMeet #{@profile.username}!", new_message_path, method: :get, params: { receiver_id: @profile.user.id}, class: "btn btn-meet form-control message-button"

            - if current_user
              .write-review.profile-info-wrapper
                %h3.text-left Write a Review:
                = form_for @review, url: reviews_path, method: "POST", remote: true do |f|
                  = hidden_field_tag "review[reviewer_id]", current_user.profile_id
                  = hidden_field_tag "review[reviewed_id]", @profile.id
                  = f.label :rating, "How would you rate your experience with this user?"
                  = f.select :rating, options_for_select(@rating_options), {}, {class: "form-control"}
                  = f.text_field :title, placeholder: "Summarize your review in a few words", class: "form-control"
                  = f.text_area :body, placeholder: "Tell people about your experience with this user", class: "form-control"
                  = f.submit "Submit Review", class: "form-control btn btn-meet"
            - else
              = link_to "Log in", new_user_session_path
              %span to write a review for this user

            #reviews
              = render @reviews

app/views/requests/_request.html.haml
%a{href: profile_path(request.profile.id)}
  %h3= request.profile.username

app/views/requests/_request_full.html.haml
%p.form-control= "#{request.activity.name} in #{request.town_city}, #{request.country}"

app/views/requests/create.js.erb
$('#requests').append("<%= j(render partial: 'requests/request_full', locals: { request: @request }) %>");

app/views/requests/new.html.haml
.new-request-wrapper
  .search-box
    = form_for @request, url: requests_path, method: "post", remote: true do |f|
      = f.hidden_field :profile_id, value: current_user.id

      I want to
      .nl-field
        %a.field-toggle select activity
        %ul
          %li select activity...
          - @activities.each_with_index do |activity, index|
            %li.select-option(data-id="#{index}")= activity[0]
        = f.select :activity_id, options_for_select(@activities), class: "inline-select", id: "activities-select"

      in
      .nl-field
        %a.field-toggle#town_city{href: ""} enter town/city
        %ul.text-input
          %li
            = f.text_field :town_city, placeholder: "enter town/city", class: "inline-text", id: "town-city-input"
            .nl-next >

      ,
      .nl-field
        %a.field-toggle#country{href: ""} enter country
        %ul.text-input
          %li
            = f.text_field :country, placeholder: "enter country", class: "inline-text", id: "country-input"
            .nl-next >

      .clearfix

      = submit_tag "Add Request", class: "inline-button"

      .nl-overlay

  #requests.col-sm-6.col-sm-offset-3
    %h3= "You want to:"
    - @requests.each do |request|
      %p.form-control= "#{request.activity.name} in #{request.town_city}, #{request.country}"

app/views/requests/search.html.haml
%script
  var searchActivity = "#{@activity}"
  var searchActivityId = #{@activity_id}
  var searchTownCity = "#{@town_city}"
  var searchCountry = "#{@country}"
  var searchMapLatLng = #{@map_lat_lng}
  var searchMapLat = #{@map_lat}
  var searchMapLng = #{@map_lng}
.content-wrapper
  #map.col-sm-9
  .col-sm-3.search-results
    %header
      %h2= "People who want to #{@activity}"

      .result-count
        Found 
        %span#resultsTotal 0
        results:
        
    #search-results

app/views/reviews/_review.html.haml
.review-container.profile-info-wrapper
  .col-sm-3
    = image_tag review.reviewer.profile.image_url || "profile_placeholder", class: "reviewer-profile"
  .review-body.col-sm-9
    %h3= review.title
    - review.rating.times do
      = image_tag "star-rating-yes", class: "review-stars"
    - (5 - review.rating).times do
      = image_tag "star-rating-no", class: "review-stars"
    %p= review.body
  .clearfix

app/views/reviews/create.js.erb
$('#reviews').append("<%= escape_javascript(render partial: 'reviews/review', locals: { review: @review }) %>");

$('#review_body').val("");

app/views/users/show.html.haml
.content-wrapper
  .col-sm-8.col-sm-offset-2.profile
    %h2= @profile.username
    = image_tag @profile.image_url || "profile-placeholder"
    %h3= "#{@profile.username} wants to:"
    - @requests.each do |request|
      %p= "#{request.activity.name} in #{request.town_city}, #{request.country}"